baseURL = 'https://tfscapegoat.vercel.app/'
languageCode = 'it-IT'
title = 'TFScapegoat'
theme = "hugo-simple"

[params]
  favicon = "/favicon.png"
  description = "A Goat Format mod of Yu-Gi-Oh! GX Tag Force."
  [params.author]
    name = "IamGroot"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
	  
[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10
  [[menu.main]]
    name = "TFScapegoat"
    pageRef = "tfscapegoat"
    weight = 20
	[[menu.main]]
    name = "Contattaci"
    pageRef = "contattaci"
    weight = 30