baseURL = 'https://tfscapegoat.vercel.app/'
languageCode = 'it-IT'
title = 'TFScapegoat'
theme = "hugo-simple"

[params]
  description = "A Goat Format mod of Yu-Gi-Oh! GX Tag Force."
  [params.author]
    name = "IamGroot"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true